name: Check PR

on:
  pull_request:
    branches:
      - main

concurrency:
  group: checking-${{ github.head_ref }}
  cancel-in-progress: false

jobs:
  check_pr_1:
    name: Check PR 1
    runs-on: ubuntu-latest

    steps:
      - name: Output HeadRef
        run: echo "${{ github.head_ref }}"

      - name: Build The Code 01
        run: |
          echo "Starting Code Build"
          sleep 1m
          echo "Finishing Code Build"

      - name: Build The Code 02
        run: |
          echo "Starting Code Build"
          sleep 1m
          echo "Finishing Code Build"
