# Example of AWS S3 deployment
name: Deploy on Amazon S3

on:
  push:
    branches:
      - master

jobs:
  deploy_staging:
    name: Deploy Staging
    runs-on: [self-hosted, default]
    timeout-minutes: 10
    env:
      TARGET: staging
      BUCKET_NAME: staging-<your_repo_bucket_name>

    steps:
      - name: Import Vault Secrets
        id: vault-secrets
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: https://vault.hellofresh.io/
          method: kubernetes
          path: tools-k8s
          role: github-actions-runners-read-default
          secrets: |
            gh-actions/repos/<your_repo_name> AWS_ACCESS_KEY_ID | AWS_ACCESS_KEY_ID;
            gh-actions/repos/<your_repo_name> AWS_SECRET_ACCESS_KEY | AWS_SECRET_ACCESS_KEY;

      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Set Project Environment
        run: npm run set:env ${{ env.TARGET }}

      - name: Build ${{ env.TARGET }}
        run: npm run build:${{ env.TARGET }}

      - name: Sync to S3
        run: aws s3 sync dist/ s3://${{ env.BUCKET_NAME }}/ --delete --cache-control max-age=86400
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.vault-secrets.outputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.vault-secrets.outputs.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-2"

  deploy_production:
    name: Deploy Production
    runs-on: [self-hosted, default]
    timeout-minutes: 10
    needs: deploy_staging
    env:
      TARGET: production
      BUCKET_NAME: <your_repo_bucket_name>

    steps:
      - name: Import Vault Secrets
        id: vault-secrets
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: https://vault.hellofresh.io/
          method: kubernetes
          path: tools-k8s
          role: github-actions-runners-read-default
          secrets: |
            gh-actions/repos/<your_repo_name> AWS_ACCESS_KEY_ID | AWS_ACCESS_KEY_ID;
            gh-actions/repos/<your_repo_name> AWS_SECRET_ACCESS_KEY | AWS_SECRET_ACCESS_KEY;

      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Set Project Environment
        run: npm run set:env ${{ env.TARGET }}

      - name: Build ${{ env.TARGET }}
        run: npm run build:${{ env.TARGET }}

      - name: Sync to S3
        run: aws s3 sync dist/ s3://${{ env.BUCKET_NAME }}/ --delete --cache-control max-age=86400
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.vault-secrets.outputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.vault-secrets.outputs.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-2"
